// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show TargetPlatform, defaultTargetPlatform, kIsWeb;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD2TKHrQUTXJjkD75WQVaAR_8WFPS5Kj80',
    appId: '1:565388049264:web:a1abda7b378c585cc3edb5',
    messagingSenderId: '565388049264',
    projectId: 'loja-virtual-pro-b586a',
    authDomain: 'loja-virtual-pro-b586a.firebaseapp.com',
    storageBucket: 'loja-virtual-pro-b586a.appspot.com',
    measurementId: 'G-TCE9L3QFJD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCFxEfG7WM5uNb_E2oIbO7IixXTThf6Upc',
    appId: '1:565388049264:android:927a8b42f6cb770bc3edb5',
    messagingSenderId: '565388049264',
    projectId: 'loja-virtual-pro-b586a',
    storageBucket: 'loja-virtual-pro-b586a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCDmievpblEpe7rq4qWjIJWF7ydgR9wnrk',
    appId: '1:565388049264:ios:d5dfea585c5e5b61c3edb5',
    messagingSenderId: '565388049264',
    projectId: 'loja-virtual-pro-b586a',
    storageBucket: 'loja-virtual-pro-b586a.appspot.com',
    iosClientId:
        '565388049264-h3u0ufjbnk0rcvdibtmccq40h0cd6g3c.apps.googleusercontent.com',
    iosBundleId: 'br.com.boarim.lojaVirtualPro',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCDmievpblEpe7rq4qWjIJWF7ydgR9wnrk',
    appId: '1:565388049264:ios:d5dfea585c5e5b61c3edb5',
    messagingSenderId: '565388049264',
    projectId: 'loja-virtual-pro-b586a',
    storageBucket: 'loja-virtual-pro-b586a.appspot.com',
    iosClientId:
        '565388049264-h3u0ufjbnk0rcvdibtmccq40h0cd6g3c.apps.googleusercontent.com',
    iosBundleId: 'br.com.boarim.lojaVirtualPro',
  );
}
